import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "@/utils/toast";



export const metadata: Metadata = {
  title: "Deep Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
